name: Feature Request
description: Ask for features that may be added to Voiid Countdown Timer!
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: "What feature do you want to get added on the **plugin** version of VCT?"
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: "Why should it be added to Voiid Countdown Timer?"
    validations:
      required: true
