name: I need help!
description: If you need help using Voiid Countdown Timer
labels: [help wanted]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your problem here."
    validations:
      required: true

  - type: dropdown
    id: vcttype
    attributes:
      label: "Which build of Voiid Countdown Timer do you use?"
      options:
        - Datapack (V1)
        - Plugin (V2)
    validations:
      required: true

  - type: input
    id: vtcversion
    attributes:
      label: "Voiid Countdown Timer version"
      placeholder: "e.g. 1.3"
    validations:
      required: true

  - type: input
    id: mcversion
    attributes:
      label: "Minecraft version"
      placeholder: "e.g. 1.21.6"
    validations:
      required: true