main: voiidstudios.vct.VoiidCountdownTimer
version: 1.4.0.3
name: VoiidCountdownTimer
authors: [Voiid Studios]
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:
  voiidcountdowntimer:
    description: Main command of Voiid Countdown Timer
    aliases:
      - vct