main: voiidstudios.vct.VoiidCountdownTimer
name: VoiidCountdownTimer
version: 2.0.0
codename: astro
authors: [Voiid Studios]
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:
  voiidcountdowntimer:
    description: Main command of Voiid Countdown Timer
    aliases:
      - vct