main: vct.voiidstudios.VoiidCountdownTimer
version: 1.4.0-rc2
name: VoiidCountdownTimer
authors: [Voiid Studios]
api-version: 1.15
softdepend: [PlaceholderAPI]

commands:
  voiidcountdowntimer:
    description: Main command of Voiid Countdown Timer
    aliases:
      - vct